name: Newman Run

on: push

jobs:
  automated-api-tests2:
    runs-on: ubuntu-latest
    container: postman/newman
    steps: 
      - uses: actions/checkout@v4
      
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
      - name: Make Directory for results
        run: 
             mkdir -p testResults
      - name: Run API Test
        run: 
             newman run "https://api.getpostman.com/collections/6481556-0298176c-000b-4892-b442-37048662f4e7?apikey=${{ secrets.POSTMAN_API_KEY2 }}" 
             --environment "https://api.getpostman.com/environments/6481556-3ebaebe0-8659-455d-bdbf-6a1dac58fb44?apikey=${{ secrets.POSTMAN_API_KEY2 }}" 
             -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html
      
      - name: Output the run Details
        uses: actions/upload-artifact@v4
        with: 
          name: RunReports
          path: testResults
          
