name: Newman Run

on: push

jobs:
  automated-api-tests2:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
      - name: Install Newman and Html reporter
        run: 
             npm install -g newman
             npm install -g newman-reporter-html-extra
      - name: Run API Test
        run: 
             newman run "https://api.getpostman.com/collections/6481556-0298176c-000b-4892-b442-37048662f4e7?apikey=${{ secrets.POSTMAN_API_KEY2 }}" 
             --environment "https://api.getpostman.com/environments/6481556-3ebaebe0-8659-455d-bdbf-6a1dac58fb44?apikey=${{ secrets.POSTMAN_API_KEY2 }}" 
             -r htmlextra
